In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

In [3]:
crop = pd.read_csv("crop_production.csv")
rainfall = pd.read_csv("rainfall in india 1901-2015.csv")

In [4]:
crop.head()
rainfall.head()

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
0,ANDAMAN & NICOBAR ISLANDS,1901,49.2,87.1,29.2,2.3,528.8,517.5,365.1,481.1,332.6,388.5,558.2,33.6,3373.2,136.3,560.3,1696.3,980.3
1,ANDAMAN & NICOBAR ISLANDS,1902,0.0,159.8,12.2,0.0,446.1,537.1,228.9,753.7,666.2,197.2,359.0,160.5,3520.7,159.8,458.3,2185.9,716.7
2,ANDAMAN & NICOBAR ISLANDS,1903,12.7,144.0,0.0,1.0,235.1,479.9,728.4,326.7,339.0,181.2,284.4,225.0,2957.4,156.7,236.1,1874.0,690.6
3,ANDAMAN & NICOBAR ISLANDS,1904,9.4,14.7,0.0,202.4,304.5,495.1,502.0,160.1,820.4,222.2,308.7,40.1,3079.6,24.1,506.9,1977.6,571.0
4,ANDAMAN & NICOBAR ISLANDS,1905,1.3,0.0,3.3,26.9,279.5,628.7,368.7,330.5,297.0,260.7,25.4,344.7,2566.7,1.3,309.7,1624.9,630.8

In [5]:
crop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246091 entries, 0 to 246090
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   State_Name     246091 non-null  object
 1   District_Name  246091 non-null  object
 2   Crop_Year      246091 non-null  int64
 3   Season         246091 non-null  object
 4   Crop           246091 non-null  object
 5   Area           246091 non-null  float64
 6   Production     242361 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.1+ MB

In [6]:
rainfall.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4116 entries, 0 to 4115
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SUBDIVISION  4116 non-null   object
 1   YEAR         4116 non-null   int64
 2   JAN          4112 non-null   float64
 3   FEB          4113 non-null   float64
 4   MAR          4110 non-null   float64
 5   APR          4112 non-null   float64
 6   MAY          4113 non-null   float64
 7   JUN          4111 non-null   float64
 8   JUL          4109 non-null   float64
 9   AUG          4112 non-null   float64
 10  SEP          4110 non-null   float64
 11  OCT          4109 non-null   float64
 12  NOV          4105 non-null   float64
 13  DEC          4106 non-null   float64
 14  ANNUAL       4090 non-null   float64
 15  Jan-Feb      4110 non-null   float64
 16  Mar-May      4107 non-null   float64
 17  Jun-Sep      4106 non-null   float64
 18  Oct-Dec      4103 non-null   float64
dtypes: float64(17), int64(1), object(1)
memory usage: 611.1+ KB

In [7]:
crop = crop.dropna(subset=["Production"])

In [8]:
rainfall = rainfall[["SUBDIVISION", "YEAR", "ANNUAL"]]

In [9]:
rainfall = rainfall.dropna(subset=["ANNUAL"])

In [10]:
rainfall = rainfall.rename(columns={
    "SUBDIVISION": "state",
    "YEAR": "year",
    "ANNUAL": "rainfall"
})

In [12]:
print(crop.columns)
print(rainfall.columns)

Index(['State_Name', 'District_Name', 'Crop_Year', 'Season', 'Crop', 'Area',
       'Production'],
      dtype='object')
Index(['state', 'year', 'rainfall'], dtype='object')

In [13]:
crop = crop.rename(columns={
    "State_Name": "state",
    "Crop_Year": "year"
})

In [14]:
print(crop.columns)

Index(['state', 'District_Name', 'year', 'Season', 'Crop', 'Area',
       'Production'],
      dtype='object')

In [15]:
crop = crop.drop(columns=["District_Name"])

In [16]:
set(crop["state"].unique()) & set(rainfall["state"].unique())

set()

In [17]:
df = pd.merge(crop, rainfall, on=["state", "year"], how="left")

In [18]:
df["yield"] = df["Production"] / df["Area"]

In [19]:
set(crop["state"].unique()) & set(rainfall["state"].unique())

set()

In [20]:
common_states = set(crop["state"].unique()) & set(rainfall["state"].unique())
len(common_states), list(common_states)[:10]

(0, [])

In [21]:
print(crop["state"].unique()[:20])

['Andaman and Nicobar Islands' 'Andhra Pradesh' 'Arunachal Pradesh'
 'Assam' 'Bihar' 'Chandigarh' 'Chhattisgarh' 'Dadra and Nagar Haveli'
 'Goa' 'Gujarat' 'Haryana' 'Himachal Pradesh' 'Jammu and Kashmir '
 'Jharkhand' 'Karnataka' 'Kerala' 'Madhya Pradesh' 'Maharashtra' 'Manipur'
 'Meghalaya']

In [22]:
print(rainfall["state"].unique()[:20])

['ANDAMAN & NICOBAR ISLANDS' 'ARUNACHAL PRADESH' 'ASSAM & MEGHALAYA'
 'NAGA MANI MIZO TRIPURA' 'SUB HIMALAYAN WEST BENGAL & SIKKIM'
 'GANGETIC WEST BENGAL' 'ORISSA' 'JHARKHAND' 'BIHAR' 'EAST UTTAR PRADESH'
 'WEST UTTAR PRADESH' 'UTTARAKHAND' 'HARYANA DELHI & CHANDIGARH' 'PUNJAB'
 'HIMACHAL PRADESH' 'JAMMU & KASHMIR' 'WEST RAJASTHAN' 'EAST RAJASTHAN'
 'WEST MADHYA PRADESH' 'EAST MADHYA PRADESH']

In [23]:
state_mapping = {
    "Assam": "ASSAM & MEGHALAYA",
    "Meghalaya": "ASSAM & MEGHALAYA",
    "Jharkhand": "JHARKHAND",
    "Bihar": "BIHAR",
    "Arunachal Pradesh": "ARUNACHAL PRADESH",
    "Andaman and Nicobar Islands": "ANDAMAN & NICOBAR ISLANDS"
}

In [24]:
crop["rainfall_state"] = crop["state"].map(state_mapping)

In [25]:
left_on=["rainfall_state", "year"]
right_on=["state", "year"]

In [27]:
sorted(crop["state"].unique())

['Andaman and Nicobar Islands',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Dadra and Nagar Haveli',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu and Kashmir ',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Telangana ',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal']

In [28]:
crop_states = {s.strip().upper() for s in crop["state"].unique()}
rainfall_states = {s.strip().upper() for s in rainfall["state"].unique()}

direct_matches = crop_states & rainfall_states

print("Number of direct matches:", len(direct_matches))
print(sorted(direct_matches))

Number of direct matches: 10
['ARUNACHAL PRADESH', 'BIHAR', 'CHHATTISGARH', 'HIMACHAL PRADESH', 'JHARKHAND', 'KERALA', 'PUNJAB', 'TAMIL NADU', 'TELANGANA', 'UTTARAKHAND']

In [30]:
rainfall = pd.read_csv("rainfall_cleaned.csv")

In [33]:
print(rainfall.head())

   year  rainfall                        state
0  1901    3373.2  Andaman and Nicobar Islands
1  1902    3520.7  Andaman and Nicobar Islands
2  1903    2957.4  Andaman and Nicobar Islands
3  1904    3079.6  Andaman and Nicobar Islands
4  1905    2566.7  Andaman and Nicobar Islands

In [34]:
print(rainfall.columns)

Index(['year', 'rainfall', 'state'], dtype='object')

In [35]:
crop = crop.rename(columns={
    "State_Name": "state",
    "Crop_Year": "year"
})

In [36]:
crop["state"] = crop["state"].str.strip()
rainfall["state"] = rainfall["state"].str.strip()

In [37]:
common_states = set(crop["state"].unique()) & set(rainfall["state"].unique())

print("Matching states:", len(common_states))
print(sorted(common_states))

Matching states: 31
['Andaman and Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']

In [38]:
print(crop.columns)

Index(['state', 'year', 'Season', 'Crop', 'Area', 'Production',
       'rainfall_state'],
      dtype='object')

In [39]:
print(rainfall.columns)

Index(['year', 'rainfall', 'state'], dtype='object')

In [40]:
crop.columns = crop.columns.str.strip()
rainfall.columns = rainfall.columns.str.strip()

In [41]:
crop = crop.drop(columns=["rainfall_state"], errors="ignore")

In [42]:
crop["state"] = crop["state"].str.strip()
rainfall["state"] = rainfall["state"].str.strip()

In [43]:
df = pd.merge(
    crop,
    rainfall,
    on=["state", "year"],
    how="left"
)

In [ ]:
df.isnull().sum()

state            0
year             0
Season           0
Crop             0
Area             0
Production       0
rainfall      1135
dtype: int64

In [45]:
print(crop["year"].min(), crop["year"].max())
print(rainfall["year"].min(), rainfall["year"].max())

1997 2015
1901 2015

In [46]:
df = df[df["year"] >= 1997]

In [47]:
df.isnull().sum()

state            0
year             0
Season           0
Crop             0
Area             0
Production       0
rainfall      1135
dtype: int64

In [48]:
df[df["rainfall"].isna()][["state", "year"]].head(20)

                        state  year
56260  Dadra and Nagar Haveli  1998
56261  Dadra and Nagar Haveli  1998
56262  Dadra and Nagar Haveli  1998
56263  Dadra and Nagar Haveli  1998
56264  Dadra and Nagar Haveli  1998
56265  Dadra and Nagar Haveli  1998
56266  Dadra and Nagar Haveli  1998
56267  Dadra and Nagar Haveli  1998
56268  Dadra and Nagar Haveli  1998
56269  Dadra and Nagar Haveli  1998
56270  Dadra and Nagar Haveli  1998
56271  Dadra and Nagar Haveli  1998
56272  Dadra and Nagar Haveli  1998
56273  Dadra and Nagar Haveli  1998
56274  Dadra and Nagar Haveli  1998
56275  Dadra and Nagar Haveli  1998
56276  Dadra and Nagar Haveli  1998
56277  Dadra and Nagar Haveli  1998
56278  Dadra and Nagar Haveli  1998
56279  Dadra and Nagar Haveli  1998

In [49]:
missing_pairs = df[df["rainfall"].isna()][["state", "year"]].drop_duplicates()
print(len(missing_pairs))
print(missing_pairs.head(30))

34
                         state  year
56260   Dadra and Nagar Haveli  1998
56281   Dadra and Nagar Haveli  1999
56299   Dadra and Nagar Haveli  2000
56317   Dadra and Nagar Haveli  2001
56334   Dadra and Nagar Haveli  2002
56351   Dadra and Nagar Haveli  2003
56368   Dadra and Nagar Haveli  2004
56387   Dadra and Nagar Haveli  2005
56406   Dadra and Nagar Haveli  2006
56425   Dadra and Nagar Haveli  2007
56434   Dadra and Nagar Haveli  2008
56443   Dadra and Nagar Haveli  2009
56452   Dadra and Nagar Haveli  2010
56471   Dadra and Nagar Haveli  2011
56489   Dadra and Nagar Haveli  2012
56507   Dadra and Nagar Haveli  2013
56515   Dadra and Nagar Haveli  2014
157686              Puducherry  1998
157694              Puducherry  1999
157710              Puducherry  2000
157726              Puducherry  2001
157737              Puducherry  2002
157747              Puducherry  2003
157759              Puducherry  2004
157772              Puducherry  2005
157784              Puducherry  2006
157792              Puducherry  2007
157807              Puducherry  2008
157821              Puducherry  2009
157835              Puducherry  2010

In [50]:
rainfall["state"].unique()

array(['Andaman and Nicobar Islands', 'Andhra Pradesh',
       'Arunachal Pradesh', 'Assam', 'Meghalaya', 'Bihar', 'Chhattisgarh',
       'Goa', 'Gujarat', 'Haryana', 'Chandigarh', 'Himachal Pradesh',
       'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala',
       'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Mizoram', 'Nagaland',
       'Tripura', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
       'Telangana', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal'],
      dtype=object)

In [51]:
valid_states = rainfall["state"].unique()
df = df[df["state"].isin(valid_states)]

In [52]:
df = pd.merge(
    crop,
    rainfall,
    on=["state", "year"],
    how="left"
)

In [53]:
df = df.dropna(subset=["rainfall"])

In [54]:
df = df[df["state"].isin(rainfall["state"].unique())]

In [56]:
missing_pairs = df[df["rainfall"].isna()][["state", "year"]].drop_duplicates()
print(missing_pairs)

Empty DataFrame
Columns: [state, year]
Index: []

In [57]:
df["rainfall"].isna().sum()

np.int64(0)

In [58]:
df["yield"] = df["Production"] / df["Area"]

In [59]:
df = df.drop(columns=["Production"])

In [60]:
y = df["yield"]

In [61]:
X = df[["state", "year", "Season", "Crop", "Area", "rainfall"]]

In [62]:
from sklearn.preprocessing import LabelEncoder

le_state = LabelEncoder()
le_crop = LabelEncoder()
le_season = LabelEncoder()

df["state"] = le_state.fit_transform(df["state"])
df["Crop"] = le_crop.fit_transform(df["Crop"])
df["Season"] = le_season.fit_transform(df["Season"])

In [63]:
X = df[["state", "year", "Season", "Crop", "Area", "rainfall"]]
y = df["yield"]

In [64]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [65]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [66]:
from sklearn.metrics import r2_score, mean_absolute_error

pred = model.predict(X_test)

print("R2 Score:", r2_score(y_test, pred))
print("MAE:", mean_absolute_error(y_test, pred))

R2 Score: 0.8365661740038447
MAE: 11.36393306203206

In [67]:
import pandas as pd

importance = pd.DataFrame({
    "feature": X.columns,
    "importance": model.feature_importances_
}).sort_values(by="importance", ascending=False)

print(importance)

    feature  importance
5  rainfall    0.495194
3      Crop    0.183106
1      year    0.155321
0     state    0.089129
4      Area    0.076617
2    Season    0.000633

In [68]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=300,
    max_depth=20,
    random_state=42
)

In [70]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\hp\anaconda3\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\users\hp\anaconda3\lib\site-packages (from xgboost) (1.16.3)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.5/101.7 MB 477.9 kB/s eta 0:03:32
   ---------------------------------------- 0.5/101.7 MB 477.9 kB/s eta 0:03:32
   ---------------------------------------- 0.5/101.7 MB 477.9 kB/s eta 0:03:32
   ---------------------------------------- 0.8/101.7 MB 385.6 kB/s eta 0:04:22
   ---------------------------------------- 0.8/101.7 MB 385.6 kB/s eta 0:04:22
   ---------------------------------------- 0.8/101.7 MB 385.6 kB/s eta 0:04:22
   ---------------------------------------- 1.0/101.7 MB 408.6 kB/s eta 0:04:07
   ---------------------------------------- 1.0/101.7 MB 408.6 kB/s eta 0:04:07
   ---------------------------------------- 1.0/101.7 MB 408.6 kB/s eta 0:04:07
    --------------------------------------- 1.3/101.7 MB 425.9 kB/s eta 0:03:56
    --------------------------------------- 1.3/101.7 MB 425.9 kB/s eta 0:03:56
    --------------------------------------- 1.6/101.7 MB 440.3 kB/s eta 0:03:48
    --------------------------------------- 1.6/101.7 MB 440.3 kB/s eta 0:03:48
    --------------------------------------- 1.8/101.7 MB 471.1 kB/s eta 0:03:32
    --------------------------------------- 1.8/101.7 MB 471.1 kB/s eta 0:03:32
    --------------------------------------- 2.1/101.7 MB 496.5 kB/s eta 0:03:21
    --------------------------------------- 2.1/101.7 MB 496.5 kB/s eta 0:03:21
    --------------------------------------- 2.4/101.7 MB 491.2 kB/s eta 0:03:23
    --------------------------------------- 2.4/101.7 MB 491.2 kB/s eta 0:03:23
    --------------------------------------- 2.4/101.7 MB 491.2 kB/s eta 0:03:23
   - -------------------------------------- 2.6/101.7 MB 484.6 kB/s eta 0:03:25
   - -------------------------------------- 2.9/101.7 MB 511.3 kB/s eta 0:03:14
   - -------------------------------------- 2.9/101.7 MB 511.3 kB/s eta 0:03:14
   - -------------------------------------- 3.1/101.7 MB 521.8 kB/s eta 0:03:09
   - -------------------------------------- 3.4/101.7 MB 550.4 kB/s eta 0:02:59
   - -------------------------------------- 3.4/101.7 MB 550.4 kB/s eta 0:02:59
   - -------------------------------------- 3.7/101.7 MB 568.1 kB/s eta 0:02:53
   - -------------------------------------- 3.9/101.7 MB 582.9 kB/s eta 0:02:48
   - -------------------------------------- 4.2/101.7 MB 595.5 kB/s eta 0:02:44
   - -------------------------------------- 4.5/101.7 MB 622.2 kB/s eta 0:02:37
   - -------------------------------------- 4.7/101.7 MB 635.1 kB/s eta 0:02:33
   - -------------------------------------- 4.7/101.7 MB 635.1 kB/s eta 0:02:33
   -- ------------------------------------- 5.2/101.7 MB 667.4 kB/s eta 0:02:25
   -- ------------------------------------- 5.2/101.7 MB 667.4 kB/s eta 0:02:25
   -- ------------------------------------- 5.5/101.7 MB 675.5 kB/s eta 0:02:23
   -- ------------------------------------- 5.8/101.7 MB 686.4 kB/s eta 0:02:20
   -- ------------------------------------- 6.3/101.7 MB 731.0 kB/s eta 0:02:11
   -- ------------------------------------- 6.8/101.7 MB 773.9 kB/s eta 0:02:03
   -- ------------------------------------- 7.1/101.7 MB 784.7 kB/s eta 0:02:01
   -- ------------------------------------- 7.6/101.7 MB 824.2 kB/s eta 0:01:55
   --- ------------------------------------ 8.1/101.7 MB 856.1 kB/s eta 0:01:50
   --- ------------------------------------ 8.4/101.7 MB 882.7 kB/s eta 0:01:46
   --- ------------------------------------ 8.7/101.7 MB 892.4 kB/s eta 0:01:45
   --- ------------------------------------ 9.2/101.7 MB 922.7 kB/s eta 0:01:41
   --- ------------------------------------ 9.4/101.7 MB 927.5 kB/s eta 0:01:40
   --- ------------------------------------ 9.7/101.7 MB 938.7 kB/s eta 0:01:38
   --- ----------------------------------- 10.2/101.7 MB 963.8 kB/s eta 0:01:35
   ---- ---------------------------------- 10.7/101.7 MB 991.9 kB/s eta 0:01:32
   ---- ----------------------------------- 11.3/101.7 MB 1.0 MB/s eta 0:01:29
   ---- ----------------------------------- 11.8/101.7 MB 1.0 MB/s eta 0:01:26
   ---- ----------------------------------- 12.1/101.7 MB 1.1 MB/s eta 0:01:25
   ---- ----------------------------------- 12.3/101.7 MB 1.1 MB/s eta 0:01:25
   ----- ---------------------------------- 13.1/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 13.1/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 13.4/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 13.6/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 13.6/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 13.6/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 13.6/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 13.6/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 13.6/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 13.6/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 13.6/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 13.6/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 13.6/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 13.6/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 13.6/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 13.6/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 13.6/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 13.6/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 13.6/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 13.6/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 13.6/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 13.6/101.7 MB 1.1 MB/s eta 0:01:21
   ----- ---------------------------------- 13.6/101.7 MB 1.1 MB/s eta 0:01:21
   ----- --------------------------------- 13.9/101.7 MB 832.9 kB/s eta 0:01:46
   ----- --------------------------------- 13.9/101.7 MB 832.9 kB/s eta 0:01:46
   ----- --------------------------------- 13.9/101.7 MB 832.9 kB/s eta 0:01:46
   ----- --------------------------------- 13.9/101.7 MB 832.9 kB/s eta 0:01:46
   ----- --------------------------------- 13.9/101.7 MB 832.9 kB/s eta 0:01:46
   ----- --------------------------------- 13.9/101.7 MB 832.9 kB/s eta 0:01:46
   ----- --------------------------------- 13.9/101.7 MB 832.9 kB/s eta 0:01:46
   ----- --------------------------------- 13.9/101.7 MB 832.9 kB/s eta 0:01:46
   ----- --------------------------------- 13.9/101.7 MB 832.9 kB/s eta 0:01:46
   ----- --------------------------------- 13.9/101.7 MB 832.9 kB/s eta 0:01:46
   ----- --------------------------------- 13.9/101.7 MB 832.9 kB/s eta 0:01:46
   ----- --------------------------------- 13.9/101.7 MB 832.9 kB/s eta 0:01:46
   ----- --------------------------------- 13.9/101.7 MB 832.9 kB/s eta 0:01:46
   ----- --------------------------------- 13.9/101.7 MB 832.9 kB/s eta 0:01:46
   ----- --------------------------------- 13.9/101.7 MB 832.9 kB/s eta 0:01:46
   ----- --------------------------------- 13.9/101.7 MB 832.9 kB/s eta 0:01:46
   ----- --------------------------------- 13.9/101.7 MB 832.9 kB/s eta 0:01:46
   ----- --------------------------------- 13.9/101.7 MB 832.9 kB/s eta 0:01:46
   ----- --------------------------------- 13.9/101.7 MB 832.9 kB/s eta 0:01:46
   ----- --------------------------------- 14.7/101.7 MB 702.5 kB/s eta 0:02:04
   ----- --------------------------------- 14.7/101.7 MB 702.5 kB/s eta 0:02:04
   ----- --------------------------------- 14.7/101.7 MB 702.5 kB/s eta 0:02:04
   ----- --------------------------------- 14.7/101.7 MB 702.5 kB/s eta 0:02:04
   ----- --------------------------------- 14.7/101.7 MB 702.5 kB/s eta 0:02:04
   ------ -------------------------------- 15.7/101.7 MB 716.9 kB/s eta 0:02:00
   ------ -------------------------------- 16.3/101.7 MB 733.9 kB/s eta 0:01:57
   ------ -------------------------------- 16.5/101.7 MB 739.8 kB/s eta 0:01:56
   ------ -------------------------------- 17.0/101.7 MB 757.6 kB/s eta 0:01:52
   ------ -------------------------------- 17.6/101.7 MB 770.8 kB/s eta 0:01:50
   ------ -------------------------------- 17.8/101.7 MB 778.6 kB/s eta 0:01:48
   ------- ------------------------------- 18.4/101.7 MB 793.2 kB/s eta 0:01:46
   ------- ------------------------------- 18.6/101.7 MB 797.7 kB/s eta 0:01:45
   ------- ------------------------------- 18.9/101.7 MB 800.7 kB/s eta 0:01:44
   ------- ------------------------------- 19.1/101.7 MB 807.1 kB/s eta 0:01:43
   ------- ------------------------------- 19.7/101.7 MB 819.5 kB/s eta 0:01:41
   ------- ------------------------------- 19.9/101.7 MB 824.7 kB/s eta 0:01:40
   ------- ------------------------------- 20.2/101.7 MB 827.5 kB/s eta 0:01:39
   ------- ------------------------------- 20.4/101.7 MB 835.5 kB/s eta 0:01:38
   -------- ------------------------------ 21.0/101.7 MB 848.1 kB/s eta 0:01:36
   -------- ------------------------------ 21.2/101.7 MB 848.0 kB/s eta 0:01:35
   -------- ------------------------------ 21.5/101.7 MB 855.6 kB/s eta 0:01:34
   -------- ------------------------------ 22.0/101.7 MB 865.5 kB/s eta 0:01:33
   -------- ------------------------------ 22.0/101.7 MB 865.5 kB/s eta 0:01:33
   -------- ------------------------------ 22.5/101.7 MB 873.2 kB/s eta 0:01:31
   -------- ------------------------------ 22.8/101.7 MB 875.5 kB/s eta 0:01:31
   -------- ------------------------------ 22.8/101.7 MB 875.5 kB/s eta 0:01:31
   -------- ------------------------------ 23.1/101.7 MB 873.5 kB/s eta 0:01:30
   --------- ----------------------------- 23.6/101.7 MB 883.0 kB/s eta 0:01:29
   --------- ----------------------------- 23.9/101.7 MB 887.2 kB/s eta 0:01:28
   --------- ----------------------------- 23.9/101.7 MB 887.2 kB/s eta 0:01:28
   --------- ----------------------------- 24.4/101.7 MB 890.5 kB/s eta 0:01:27
   --------- ----------------------------- 24.6/101.7 MB 893.4 kB/s eta 0:01:27
   --------- ----------------------------- 25.2/101.7 MB 903.9 kB/s eta 0:01:25
   --------- ----------------------------- 25.2/101.7 MB 903.9 kB/s eta 0:01:25
   --------- ----------------------------- 25.2/101.7 MB 903.9 kB/s eta 0:01:25
   --------- ----------------------------- 25.7/101.7 MB 903.6 kB/s eta 0:01:25
   --------- ----------------------------- 26.0/101.7 MB 908.1 kB/s eta 0:01:24
   ---------- ---------------------------- 26.2/101.7 MB 910.5 kB/s eta 0:01:23
   ---------- ---------------------------- 26.5/101.7 MB 914.6 kB/s eta 0:01:23
   ---------- ---------------------------- 27.0/101.7 MB 924.5 kB/s eta 0:01:21
   ---------- ---------------------------- 27.5/101.7 MB 934.1 kB/s eta 0:01:20
   ---------- ---------------------------- 27.8/101.7 MB 939.5 kB/s eta 0:01:19
   ---------- ---------------------------- 28.3/101.7 MB 946.3 kB/s eta 0:01:18
   ---------- ---------------------------- 28.3/101.7 MB 946.3 kB/s eta 0:01:18
   ----------- --------------------------- 28.8/101.7 MB 958.3 kB/s eta 0:01:17
   ----------- --------------------------- 29.1/101.7 MB 962.0 kB/s eta 0:01:16
   ----------- --------------------------- 29.1/101.7 MB 962.0 kB/s eta 0:01:16
   ----------- --------------------------- 29.6/101.7 MB 982.5 kB/s eta 0:01:14
   ----------- --------------------------- 29.6/101.7 MB 982.5 kB/s eta 0:01:14
   ----------- --------------------------- 29.9/101.7 MB 980.4 kB/s eta 0:01:14
   ----------- --------------------------- 29.9/101.7 MB 980.4 kB/s eta 0:01:14
   ----------- --------------------------- 30.1/101.7 MB 987.1 kB/s eta 0:01:13
   ----------- --------------------------- 30.4/101.7 MB 983.4 kB/s eta 0:01:13
   ----------- --------------------------- 30.7/101.7 MB 991.0 kB/s eta 0:01:12
   ------------ --------------------------- 31.2/101.7 MB 1.0 MB/s eta 0:01:11
   ------------ --------------------------- 31.5/101.7 MB 1.0 MB/s eta 0:01:10
   ------------ --------------------------- 31.5/101.7 MB 1.0 MB/s eta 0:01:10
   ------------ --------------------------- 31.5/101.7 MB 1.0 MB/s eta 0:01:10
   ------------ --------------------------- 31.5/101.7 MB 1.0 MB/s eta 0:01:10
   ------------ --------------------------- 31.5/101.7 MB 1.0 MB/s eta 0:01:10
   ------------ --------------------------- 31.5/101.7 MB 1.0 MB/s eta 0:01:10
   ------------ --------------------------- 32.2/101.7 MB 1.0 MB/s eta 0:01:09
   ------------ --------------------------- 32.5/101.7 MB 1.0 MB/s eta 0:01:08
   ------------ --------------------------- 32.8/101.7 MB 1.0 MB/s eta 0:01:08
   ------------ --------------------------- 33.0/101.7 MB 1.0 MB/s eta 0:01:07
   ------------- -------------------------- 33.6/101.7 MB 1.0 MB/s eta 0:01:05
   ------------- -------------------------- 34.1/101.7 MB 1.1 MB/s eta 0:01:05
   ------------- -------------------------- 34.1/101.7 MB 1.1 MB/s eta 0:01:05
   ------------- -------------------------- 34.6/101.7 MB 1.1 MB/s eta 0:01:04
   ------------- -------------------------- 35.1/101.7 MB 1.1 MB/s eta 0:01:02
   -------------- ------------------------- 35.7/101.7 MB 1.1 MB/s eta 0:01:01
   -------------- ------------------------- 35.9/101.7 MB 1.1 MB/s eta 0:01:01
   -------------- ------------------------- 36.4/101.7 MB 1.1 MB/s eta 0:01:00
   -------------- ------------------------- 36.4/101.7 MB 1.1 MB/s eta 0:01:00
   -------------- ------------------------- 37.0/101.7 MB 1.1 MB/s eta 0:00:59
   -------------- ------------------------- 37.2/101.7 MB 1.1 MB/s eta 0:00:59
   -------------- ------------------------- 37.7/101.7 MB 1.1 MB/s eta 0:00:58
   --------------- ------------------------ 38.3/101.7 MB 1.1 MB/s eta 0:00:57
   --------------- ------------------------ 39.1/101.7 MB 1.1 MB/s eta 0:00:55
   --------------- ------------------------ 39.6/101.7 MB 1.1 MB/s eta 0:00:55
   --------------- ------------------------ 40.1/101.7 MB 1.2 MB/s eta 0:00:54
   --------------- ------------------------ 40.6/101.7 MB 1.2 MB/s eta 0:00:53
   ---------------- ----------------------- 41.2/101.7 MB 1.2 MB/s eta 0:00:52
   ---------------- ----------------------- 41.7/101.7 MB 1.2 MB/s eta 0:00:52
   ---------------- ----------------------- 41.9/101.7 MB 1.2 MB/s eta 0:00:51
   ---------------- ----------------------- 42.5/101.7 MB 1.2 MB/s eta 0:00:51
   ---------------- ----------------------- 42.7/101.7 MB 1.2 MB/s eta 0:00:51
   ----------------- ---------------------- 43.5/101.7 MB 1.2 MB/s eta 0:00:49
   ----------------- ---------------------- 44.0/101.7 MB 1.2 MB/s eta 0:00:49
   ----------------- ---------------------- 44.6/101.7 MB 1.2 MB/s eta 0:00:48
   ----------------- ---------------------- 44.8/101.7 MB 1.2 MB/s eta 0:00:48
   ----------------- ---------------------- 45.4/101.7 MB 1.2 MB/s eta 0:00:48
   ----------------- ---------------------- 45.6/101.7 MB 1.2 MB/s eta 0:00:47
   ------------------ --------------------- 46.1/101.7 MB 1.2 MB/s eta 0:00:47
   ------------------ --------------------- 46.1/101.7 MB 1.2 MB/s eta 0:00:47
   ------------------ --------------------- 46.1/101.7 MB 1.2 MB/s eta 0:00:47
   ------------------ --------------------- 47.2/101.7 MB 1.2 MB/s eta 0:00:47
   ------------------ --------------------- 47.4/101.7 MB 1.2 MB/s eta 0:00:46
   ------------------ --------------------- 48.0/101.7 MB 1.2 MB/s eta 0:00:46
   ------------------ --------------------- 48.2/101.7 MB 1.2 MB/s eta 0:00:45
   ------------------ --------------------- 48.2/101.7 MB 1.2 MB/s eta 0:00:45
   ------------------- -------------------- 48.5/101.7 MB 1.2 MB/s eta 0:00:46
   ------------------- -------------------- 49.0/101.7 MB 1.4 MB/s eta 0:00:39
   ------------------- -------------------- 49.3/101.7 MB 1.4 MB/s eta 0:00:39
   ------------------- -------------------- 49.5/101.7 MB 1.4 MB/s eta 0:00:39
   ------------------- -------------------- 49.8/101.7 MB 1.4 MB/s eta 0:00:39
   ------------------- -------------------- 50.6/101.7 MB 1.4 MB/s eta 0:00:38
   ------------------- -------------------- 50.6/101.7 MB 1.4 MB/s eta 0:00:38
   -------------------- ------------------- 51.1/101.7 MB 1.4 MB/s eta 0:00:37
   -------------------- ------------------- 51.6/101.7 MB 1.4 MB/s eta 0:00:37
   -------------------- ------------------- 52.2/101.7 MB 1.4 MB/s eta 0:00:36
   -------------------- ------------------- 52.7/101.7 MB 1.4 MB/s eta 0:00:36
   -------------------- ------------------- 53.0/101.7 MB 1.4 MB/s eta 0:00:35
   -------------------- ------------------- 53.2/101.7 MB 1.4 MB/s eta 0:00:35
   --------------------- ------------------ 53.7/101.7 MB 1.4 MB/s eta 0:00:35
   --------------------- ------------------ 54.0/101.7 MB 1.4 MB/s eta 0:00:34
   --------------------- ------------------ 54.3/101.7 MB 1.4 MB/s eta 0:00:34
   --------------------- ------------------ 54.5/101.7 MB 1.4 MB/s eta 0:00:34
   --------------------- ------------------ 55.8/101.7 MB 1.4 MB/s eta 0:00:32
   ---------------------- ----------------- 56.4/101.7 MB 1.4 MB/s eta 0:00:32
   ---------------------- ----------------- 56.6/101.7 MB 1.4 MB/s eta 0:00:32
   ---------------------- ----------------- 57.4/101.7 MB 1.5 MB/s eta 0:00:31
   ---------------------- ----------------- 57.7/101.7 MB 1.5 MB/s eta 0:00:31
   ---------------------- ----------------- 58.2/101.7 MB 1.7 MB/s eta 0:00:26
   ----------------------- ---------------- 59.0/101.7 MB 1.7 MB/s eta 0:00:26
   ----------------------- ---------------- 59.5/101.7 MB 1.7 MB/s eta 0:00:25
   ----------------------- ---------------- 60.3/101.7 MB 1.7 MB/s eta 0:00:25
   ----------------------- ---------------- 60.6/101.7 MB 1.7 MB/s eta 0:00:24
   ------------------------ --------------- 61.1/101.7 MB 1.7 MB/s eta 0:00:24
   ------------------------ --------------- 61.6/101.7 MB 1.7 MB/s eta 0:00:24
   ------------------------ --------------- 61.9/101.7 MB 1.7 MB/s eta 0:00:24
   ------------------------ --------------- 62.4/101.7 MB 1.7 MB/s eta 0:00:23
   ------------------------ --------------- 63.2/101.7 MB 1.7 MB/s eta 0:00:23
   ------------------------- -------------- 64.0/101.7 MB 1.8 MB/s eta 0:00:22
   ------------------------- -------------- 64.7/101.7 MB 1.8 MB/s eta 0:00:21
   ------------------------- -------------- 65.5/101.7 MB 1.8 MB/s eta 0:00:21
   -------------------------- ------------- 66.3/101.7 MB 1.8 MB/s eta 0:00:20
   -------------------------- ------------- 67.1/101.7 MB 1.8 MB/s eta 0:00:20
   -------------------------- ------------- 68.2/101.7 MB 1.8 MB/s eta 0:00:19
   -------------------------- ------------- 68.4/101.7 MB 1.8 MB/s eta 0:00:19
   --------------------------- ------------ 68.9/101.7 MB 1.8 MB/s eta 0:00:18
   --------------------------- ------------ 69.5/101.7 MB 1.8 MB/s eta 0:00:18
   --------------------------- ------------ 70.0/101.7 MB 1.9 MB/s eta 0:00:17
   --------------------------- ------------ 70.5/101.7 MB 1.9 MB/s eta 0:00:17
   --------------------------- ------------ 70.5/101.7 MB 1.9 MB/s eta 0:00:17

In [69]:
from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6
)

ModuleNotFoundError: No module named 'xgboost'